### ISSUE TITLE
Animation Options in startSpinner() Not Working

### ISSUE THREAD

**Issue by anonuser36** [trafficonese/leaflet.extras2#65]
Hello! I'm trying to use implement the package's **Spinner**, and while I'm able to get it to work perfectly fine, I've found that the **animation customization** doesn't seem to work. As illustrated below, all of the other list options work correctly, it's only the animation option that doesn't work. In case it was an issue with not having the css info to inform the animation, I added the below code (taken from the spin.js webpage linked in the guide) to my css file, but that didn't solve the issue either. No animations except the default seem to be available. I also tried using smaller parts of the class names like "line-shrink" and "shrink" and "line-fade", etc. however those don't work either. Has anyone else had this problem and was able to solve it?

**CSS code taken from spin.js:**
```css
@keyframes spinner-line-shrink {
  0%, 25%, 100% {
    /* minimum scale and opacity */
    transform: scale(0.5);
    opacity: 0.25;
  }
  26% {
    transform: scale(1);
    opacity: 1;
  }
}
```
**Reprex:**
```r
leafletProxy("map") %>%
          clearShapes() %>% clearControls() %>% # clear existing stuff before redrawing...
          # Goal: add leaflet spinner functionality using the leaflet.extras2 package which incorporates the Leaflet Spinner plugin.
          #       to use, simply addSpinner() startSpinner() * do the adding/rendering * stopSpinner()
          ##########################
          leaflet.extras2::addSpinner()%>%
          leaflet.extras2::startSpinner(options=list("lines"=8, "length"=0, "width"=38, "radius"=67, "scale"=0.9, "color"="#2186bb", "animation"="spinner-line-shrink")) # This starts the spinner off                                                                                                           
        ## add the new layers ##
        leaflet.extras2::stopSpinner()
```
Thank you for your help!
